version: '3'
services:
  order-service:
    hostname: order-service
    container_name: order-service
    image: <dockerhub-username>/order-service
    ports: 
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    links: 
      - rabbitmq
  payment-service:
    hostname: payment-service
    container_name: payment-service
    image: <dockerhub-username>/payment-service
    # depends_on:
    #   - rabbitmq
    #   - order
    depends_on:
      order-service:
        condition: service_started
    links:
      - rabbitmq
  storage-service:
    hostname: storage-service
    container_name: storage-service
    image: <dockerhub-username>/storage-service
    depends_on:
      - order-service
    links:
      - rabbitmq
  rabbitmq:
    # command: bash -c "apt-get update && apt-get -y install curl"
    hostname: rabbitmq
    container_name: rabbitmq
    image: <dockerhub-username>/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 5s
        timeout: 10s
        retries: 5